name: hips-cdp/hips-cdp CI
on:
  push:
    branches:
    - "*"
jobs:
  build:
    name: Validate ARM templates
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: "./.github/actions/ci_cd_steps_validate_templates"
      with:
        validationManagementGroup: RayTestMG
        validationSubscription: MSK Server Solutions
        validationResourceGroup: hccp-ci-validation
        validateRegion: East US 2